 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/causes", type: :request do
  # Cause. As you add validations to Cause, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cause.create! valid_attributes
      get causes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cause = Cause.create! valid_attributes
      get cause_url(cause)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cause_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cause = Cause.create! valid_attributes
      get edit_cause_url(cause)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cause" do
        expect {
          post causes_url, params: { cause: valid_attributes }
        }.to change(Cause, :count).by(1)
      end

      it "redirects to the created cause" do
        post causes_url, params: { cause: valid_attributes }
        expect(response).to redirect_to(cause_url(Cause.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cause" do
        expect {
          post causes_url, params: { cause: invalid_attributes }
        }.to change(Cause, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post causes_url, params: { cause: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cause" do
        cause = Cause.create! valid_attributes
        patch cause_url(cause), params: { cause: new_attributes }
        cause.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cause" do
        cause = Cause.create! valid_attributes
        patch cause_url(cause), params: { cause: new_attributes }
        cause.reload
        expect(response).to redirect_to(cause_url(cause))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cause = Cause.create! valid_attributes
        patch cause_url(cause), params: { cause: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cause" do
      cause = Cause.create! valid_attributes
      expect {
        delete cause_url(cause)
      }.to change(Cause, :count).by(-1)
    end

    it "redirects to the causes list" do
      cause = Cause.create! valid_attributes
      delete cause_url(cause)
      expect(response).to redirect_to(causes_url)
    end
  end
end
