 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/classifications", type: :request do
  # Classification. As you add validations to Classification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Classification.create! valid_attributes
      get classifications_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      classification = Classification.create! valid_attributes
      get classification_url(classification)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_classification_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      classification = Classification.create! valid_attributes
      get edit_classification_url(classification)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Classification" do
        expect {
          post classifications_url, params: { classification: valid_attributes }
        }.to change(Classification, :count).by(1)
      end

      it "redirects to the created classification" do
        post classifications_url, params: { classification: valid_attributes }
        expect(response).to redirect_to(classification_url(Classification.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Classification" do
        expect {
          post classifications_url, params: { classification: invalid_attributes }
        }.to change(Classification, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post classifications_url, params: { classification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested classification" do
        classification = Classification.create! valid_attributes
        patch classification_url(classification), params: { classification: new_attributes }
        classification.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the classification" do
        classification = Classification.create! valid_attributes
        patch classification_url(classification), params: { classification: new_attributes }
        classification.reload
        expect(response).to redirect_to(classification_url(classification))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        classification = Classification.create! valid_attributes
        patch classification_url(classification), params: { classification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested classification" do
      classification = Classification.create! valid_attributes
      expect {
        delete classification_url(classification)
      }.to change(Classification, :count).by(-1)
    end

    it "redirects to the classifications list" do
      classification = Classification.create! valid_attributes
      delete classification_url(classification)
      expect(response).to redirect_to(classifications_url)
    end
  end
end
