 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/incidentsubcategories", type: :request do
  # Incidentsubcategory. As you add validations to Incidentsubcategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Incidentsubcategory.create! valid_attributes
      get incidentsubcategories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      incidentsubcategory = Incidentsubcategory.create! valid_attributes
      get incidentsubcategory_url(incidentsubcategory)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_incidentsubcategory_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      incidentsubcategory = Incidentsubcategory.create! valid_attributes
      get edit_incidentsubcategory_url(incidentsubcategory)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Incidentsubcategory" do
        expect {
          post incidentsubcategories_url, params: { incidentsubcategory: valid_attributes }
        }.to change(Incidentsubcategory, :count).by(1)
      end

      it "redirects to the created incidentsubcategory" do
        post incidentsubcategories_url, params: { incidentsubcategory: valid_attributes }
        expect(response).to redirect_to(incidentsubcategory_url(Incidentsubcategory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Incidentsubcategory" do
        expect {
          post incidentsubcategories_url, params: { incidentsubcategory: invalid_attributes }
        }.to change(Incidentsubcategory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post incidentsubcategories_url, params: { incidentsubcategory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested incidentsubcategory" do
        incidentsubcategory = Incidentsubcategory.create! valid_attributes
        patch incidentsubcategory_url(incidentsubcategory), params: { incidentsubcategory: new_attributes }
        incidentsubcategory.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the incidentsubcategory" do
        incidentsubcategory = Incidentsubcategory.create! valid_attributes
        patch incidentsubcategory_url(incidentsubcategory), params: { incidentsubcategory: new_attributes }
        incidentsubcategory.reload
        expect(response).to redirect_to(incidentsubcategory_url(incidentsubcategory))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        incidentsubcategory = Incidentsubcategory.create! valid_attributes
        patch incidentsubcategory_url(incidentsubcategory), params: { incidentsubcategory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested incidentsubcategory" do
      incidentsubcategory = Incidentsubcategory.create! valid_attributes
      expect {
        delete incidentsubcategory_url(incidentsubcategory)
      }.to change(Incidentsubcategory, :count).by(-1)
    end

    it "redirects to the incidentsubcategories list" do
      incidentsubcategory = Incidentsubcategory.create! valid_attributes
      delete incidentsubcategory_url(incidentsubcategory)
      expect(response).to redirect_to(incidentsubcategories_url)
    end
  end
end
