 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/injurytypes", type: :request do
  # Injurytype. As you add validations to Injurytype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Injurytype.create! valid_attributes
      get injurytypes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      injurytype = Injurytype.create! valid_attributes
      get injurytype_url(injurytype)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_injurytype_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      injurytype = Injurytype.create! valid_attributes
      get edit_injurytype_url(injurytype)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Injurytype" do
        expect {
          post injurytypes_url, params: { injurytype: valid_attributes }
        }.to change(Injurytype, :count).by(1)
      end

      it "redirects to the created injurytype" do
        post injurytypes_url, params: { injurytype: valid_attributes }
        expect(response).to redirect_to(injurytype_url(Injurytype.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Injurytype" do
        expect {
          post injurytypes_url, params: { injurytype: invalid_attributes }
        }.to change(Injurytype, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post injurytypes_url, params: { injurytype: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested injurytype" do
        injurytype = Injurytype.create! valid_attributes
        patch injurytype_url(injurytype), params: { injurytype: new_attributes }
        injurytype.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the injurytype" do
        injurytype = Injurytype.create! valid_attributes
        patch injurytype_url(injurytype), params: { injurytype: new_attributes }
        injurytype.reload
        expect(response).to redirect_to(injurytype_url(injurytype))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        injurytype = Injurytype.create! valid_attributes
        patch injurytype_url(injurytype), params: { injurytype: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested injurytype" do
      injurytype = Injurytype.create! valid_attributes
      expect {
        delete injurytype_url(injurytype)
      }.to change(Injurytype, :count).by(-1)
    end

    it "redirects to the injurytypes list" do
      injurytype = Injurytype.create! valid_attributes
      delete injurytype_url(injurytype)
      expect(response).to redirect_to(injurytypes_url)
    end
  end
end
