 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/investigationinjurytypes", type: :request do
  # Investigationinjurytype. As you add validations to Investigationinjurytype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Investigationinjurytype.create! valid_attributes
      get investigationinjurytypes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      investigationinjurytype = Investigationinjurytype.create! valid_attributes
      get investigationinjurytype_url(investigationinjurytype)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_investigationinjurytype_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      investigationinjurytype = Investigationinjurytype.create! valid_attributes
      get edit_investigationinjurytype_url(investigationinjurytype)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Investigationinjurytype" do
        expect {
          post investigationinjurytypes_url, params: { investigationinjurytype: valid_attributes }
        }.to change(Investigationinjurytype, :count).by(1)
      end

      it "redirects to the created investigationinjurytype" do
        post investigationinjurytypes_url, params: { investigationinjurytype: valid_attributes }
        expect(response).to redirect_to(investigationinjurytype_url(Investigationinjurytype.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Investigationinjurytype" do
        expect {
          post investigationinjurytypes_url, params: { investigationinjurytype: invalid_attributes }
        }.to change(Investigationinjurytype, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post investigationinjurytypes_url, params: { investigationinjurytype: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested investigationinjurytype" do
        investigationinjurytype = Investigationinjurytype.create! valid_attributes
        patch investigationinjurytype_url(investigationinjurytype), params: { investigationinjurytype: new_attributes }
        investigationinjurytype.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the investigationinjurytype" do
        investigationinjurytype = Investigationinjurytype.create! valid_attributes
        patch investigationinjurytype_url(investigationinjurytype), params: { investigationinjurytype: new_attributes }
        investigationinjurytype.reload
        expect(response).to redirect_to(investigationinjurytype_url(investigationinjurytype))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        investigationinjurytype = Investigationinjurytype.create! valid_attributes
        patch investigationinjurytype_url(investigationinjurytype), params: { investigationinjurytype: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested investigationinjurytype" do
      investigationinjurytype = Investigationinjurytype.create! valid_attributes
      expect {
        delete investigationinjurytype_url(investigationinjurytype)
      }.to change(Investigationinjurytype, :count).by(-1)
    end

    it "redirects to the investigationinjurytypes list" do
      investigationinjurytype = Investigationinjurytype.create! valid_attributes
      delete investigationinjurytype_url(investigationinjurytype)
      expect(response).to redirect_to(investigationinjurytypes_url)
    end
  end
end
