 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/investigationactions", type: :request do
  # Investigationaction. As you add validations to Investigationaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Investigationaction.create! valid_attributes
      get investigationactions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      investigationaction = Investigationaction.create! valid_attributes
      get investigationaction_url(investigationaction)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_investigationaction_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      investigationaction = Investigationaction.create! valid_attributes
      get edit_investigationaction_url(investigationaction)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Investigationaction" do
        expect {
          post investigationactions_url, params: { investigationaction: valid_attributes }
        }.to change(Investigationaction, :count).by(1)
      end

      it "redirects to the created investigationaction" do
        post investigationactions_url, params: { investigationaction: valid_attributes }
        expect(response).to redirect_to(investigationaction_url(Investigationaction.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Investigationaction" do
        expect {
          post investigationactions_url, params: { investigationaction: invalid_attributes }
        }.to change(Investigationaction, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post investigationactions_url, params: { investigationaction: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested investigationaction" do
        investigationaction = Investigationaction.create! valid_attributes
        patch investigationaction_url(investigationaction), params: { investigationaction: new_attributes }
        investigationaction.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the investigationaction" do
        investigationaction = Investigationaction.create! valid_attributes
        patch investigationaction_url(investigationaction), params: { investigationaction: new_attributes }
        investigationaction.reload
        expect(response).to redirect_to(investigationaction_url(investigationaction))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        investigationaction = Investigationaction.create! valid_attributes
        patch investigationaction_url(investigationaction), params: { investigationaction: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested investigationaction" do
      investigationaction = Investigationaction.create! valid_attributes
      expect {
        delete investigationaction_url(investigationaction)
      }.to change(Investigationaction, :count).by(-1)
    end

    it "redirects to the investigationactions list" do
      investigationaction = Investigationaction.create! valid_attributes
      delete investigationaction_url(investigationaction)
      expect(response).to redirect_to(investigationactions_url)
    end
  end
end
