 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/investigationclassifications", type: :request do
  # Investigationclassification. As you add validations to Investigationclassification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Investigationclassification.create! valid_attributes
      get investigationclassifications_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      investigationclassification = Investigationclassification.create! valid_attributes
      get investigationclassification_url(investigationclassification)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_investigationclassification_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      investigationclassification = Investigationclassification.create! valid_attributes
      get edit_investigationclassification_url(investigationclassification)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Investigationclassification" do
        expect {
          post investigationclassifications_url, params: { investigationclassification: valid_attributes }
        }.to change(Investigationclassification, :count).by(1)
      end

      it "redirects to the created investigationclassification" do
        post investigationclassifications_url, params: { investigationclassification: valid_attributes }
        expect(response).to redirect_to(investigationclassification_url(Investigationclassification.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Investigationclassification" do
        expect {
          post investigationclassifications_url, params: { investigationclassification: invalid_attributes }
        }.to change(Investigationclassification, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post investigationclassifications_url, params: { investigationclassification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested investigationclassification" do
        investigationclassification = Investigationclassification.create! valid_attributes
        patch investigationclassification_url(investigationclassification), params: { investigationclassification: new_attributes }
        investigationclassification.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the investigationclassification" do
        investigationclassification = Investigationclassification.create! valid_attributes
        patch investigationclassification_url(investigationclassification), params: { investigationclassification: new_attributes }
        investigationclassification.reload
        expect(response).to redirect_to(investigationclassification_url(investigationclassification))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        investigationclassification = Investigationclassification.create! valid_attributes
        patch investigationclassification_url(investigationclassification), params: { investigationclassification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested investigationclassification" do
      investigationclassification = Investigationclassification.create! valid_attributes
      expect {
        delete investigationclassification_url(investigationclassification)
      }.to change(Investigationclassification, :count).by(-1)
    end

    it "redirects to the investigationclassifications list" do
      investigationclassification = Investigationclassification.create! valid_attributes
      delete investigationclassification_url(investigationclassification)
      expect(response).to redirect_to(investigationclassifications_url)
    end
  end
end
