 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/investigationinjurylocations", type: :request do
  # Investigationinjurylocation. As you add validations to Investigationinjurylocation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Investigationinjurylocation.create! valid_attributes
      get investigationinjurylocations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      investigationinjurylocation = Investigationinjurylocation.create! valid_attributes
      get investigationinjurylocation_url(investigationinjurylocation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_investigationinjurylocation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      investigationinjurylocation = Investigationinjurylocation.create! valid_attributes
      get edit_investigationinjurylocation_url(investigationinjurylocation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Investigationinjurylocation" do
        expect {
          post investigationinjurylocations_url, params: { investigationinjurylocation: valid_attributes }
        }.to change(Investigationinjurylocation, :count).by(1)
      end

      it "redirects to the created investigationinjurylocation" do
        post investigationinjurylocations_url, params: { investigationinjurylocation: valid_attributes }
        expect(response).to redirect_to(investigationinjurylocation_url(Investigationinjurylocation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Investigationinjurylocation" do
        expect {
          post investigationinjurylocations_url, params: { investigationinjurylocation: invalid_attributes }
        }.to change(Investigationinjurylocation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post investigationinjurylocations_url, params: { investigationinjurylocation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested investigationinjurylocation" do
        investigationinjurylocation = Investigationinjurylocation.create! valid_attributes
        patch investigationinjurylocation_url(investigationinjurylocation), params: { investigationinjurylocation: new_attributes }
        investigationinjurylocation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the investigationinjurylocation" do
        investigationinjurylocation = Investigationinjurylocation.create! valid_attributes
        patch investigationinjurylocation_url(investigationinjurylocation), params: { investigationinjurylocation: new_attributes }
        investigationinjurylocation.reload
        expect(response).to redirect_to(investigationinjurylocation_url(investigationinjurylocation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        investigationinjurylocation = Investigationinjurylocation.create! valid_attributes
        patch investigationinjurylocation_url(investigationinjurylocation), params: { investigationinjurylocation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested investigationinjurylocation" do
      investigationinjurylocation = Investigationinjurylocation.create! valid_attributes
      expect {
        delete investigationinjurylocation_url(investigationinjurylocation)
      }.to change(Investigationinjurylocation, :count).by(-1)
    end

    it "redirects to the investigationinjurylocations list" do
      investigationinjurylocation = Investigationinjurylocation.create! valid_attributes
      delete investigationinjurylocation_url(investigationinjurylocation)
      expect(response).to redirect_to(investigationinjurylocations_url)
    end
  end
end
