 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/investigationcauses", type: :request do
  # Investigationcause. As you add validations to Investigationcause, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Investigationcause.create! valid_attributes
      get investigationcauses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      investigationcause = Investigationcause.create! valid_attributes
      get investigationcause_url(investigationcause)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_investigationcause_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      investigationcause = Investigationcause.create! valid_attributes
      get edit_investigationcause_url(investigationcause)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Investigationcause" do
        expect {
          post investigationcauses_url, params: { investigationcause: valid_attributes }
        }.to change(Investigationcause, :count).by(1)
      end

      it "redirects to the created investigationcause" do
        post investigationcauses_url, params: { investigationcause: valid_attributes }
        expect(response).to redirect_to(investigationcause_url(Investigationcause.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Investigationcause" do
        expect {
          post investigationcauses_url, params: { investigationcause: invalid_attributes }
        }.to change(Investigationcause, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post investigationcauses_url, params: { investigationcause: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested investigationcause" do
        investigationcause = Investigationcause.create! valid_attributes
        patch investigationcause_url(investigationcause), params: { investigationcause: new_attributes }
        investigationcause.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the investigationcause" do
        investigationcause = Investigationcause.create! valid_attributes
        patch investigationcause_url(investigationcause), params: { investigationcause: new_attributes }
        investigationcause.reload
        expect(response).to redirect_to(investigationcause_url(investigationcause))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        investigationcause = Investigationcause.create! valid_attributes
        patch investigationcause_url(investigationcause), params: { investigationcause: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested investigationcause" do
      investigationcause = Investigationcause.create! valid_attributes
      expect {
        delete investigationcause_url(investigationcause)
      }.to change(Investigationcause, :count).by(-1)
    end

    it "redirects to the investigationcauses list" do
      investigationcause = Investigationcause.create! valid_attributes
      delete investigationcause_url(investigationcause)
      expect(response).to redirect_to(investigationcauses_url)
    end
  end
end
