 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/subclassifications", type: :request do
  # Subclassification. As you add validations to Subclassification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Subclassification.create! valid_attributes
      get subclassifications_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      subclassification = Subclassification.create! valid_attributes
      get subclassification_url(subclassification)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_subclassification_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      subclassification = Subclassification.create! valid_attributes
      get edit_subclassification_url(subclassification)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Subclassification" do
        expect {
          post subclassifications_url, params: { subclassification: valid_attributes }
        }.to change(Subclassification, :count).by(1)
      end

      it "redirects to the created subclassification" do
        post subclassifications_url, params: { subclassification: valid_attributes }
        expect(response).to redirect_to(subclassification_url(Subclassification.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Subclassification" do
        expect {
          post subclassifications_url, params: { subclassification: invalid_attributes }
        }.to change(Subclassification, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post subclassifications_url, params: { subclassification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested subclassification" do
        subclassification = Subclassification.create! valid_attributes
        patch subclassification_url(subclassification), params: { subclassification: new_attributes }
        subclassification.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the subclassification" do
        subclassification = Subclassification.create! valid_attributes
        patch subclassification_url(subclassification), params: { subclassification: new_attributes }
        subclassification.reload
        expect(response).to redirect_to(subclassification_url(subclassification))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        subclassification = Subclassification.create! valid_attributes
        patch subclassification_url(subclassification), params: { subclassification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested subclassification" do
      subclassification = Subclassification.create! valid_attributes
      expect {
        delete subclassification_url(subclassification)
      }.to change(Subclassification, :count).by(-1)
    end

    it "redirects to the subclassifications list" do
      subclassification = Subclassification.create! valid_attributes
      delete subclassification_url(subclassification)
      expect(response).to redirect_to(subclassifications_url)
    end
  end
end
