 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/victims", type: :request do
  # Victim. As you add validations to Victim, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Victim.create! valid_attributes
      get victims_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      victim = Victim.create! valid_attributes
      get victim_url(victim)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_victim_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      victim = Victim.create! valid_attributes
      get edit_victim_url(victim)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Victim" do
        expect {
          post victims_url, params: { victim: valid_attributes }
        }.to change(Victim, :count).by(1)
      end

      it "redirects to the created victim" do
        post victims_url, params: { victim: valid_attributes }
        expect(response).to redirect_to(victim_url(Victim.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Victim" do
        expect {
          post victims_url, params: { victim: invalid_attributes }
        }.to change(Victim, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post victims_url, params: { victim: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested victim" do
        victim = Victim.create! valid_attributes
        patch victim_url(victim), params: { victim: new_attributes }
        victim.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the victim" do
        victim = Victim.create! valid_attributes
        patch victim_url(victim), params: { victim: new_attributes }
        victim.reload
        expect(response).to redirect_to(victim_url(victim))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        victim = Victim.create! valid_attributes
        patch victim_url(victim), params: { victim: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested victim" do
      victim = Victim.create! valid_attributes
      expect {
        delete victim_url(victim)
      }.to change(Victim, :count).by(-1)
    end

    it "redirects to the victims list" do
      victim = Victim.create! valid_attributes
      delete victim_url(victim)
      expect(response).to redirect_to(victims_url)
    end
  end
end
