 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/witnesses", type: :request do
  # Witness. As you add validations to Witness, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Witness.create! valid_attributes
      get witnesses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      witness = Witness.create! valid_attributes
      get witness_url(witness)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_witness_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      witness = Witness.create! valid_attributes
      get edit_witness_url(witness)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Witness" do
        expect {
          post witnesses_url, params: { witness: valid_attributes }
        }.to change(Witness, :count).by(1)
      end

      it "redirects to the created witness" do
        post witnesses_url, params: { witness: valid_attributes }
        expect(response).to redirect_to(witness_url(Witness.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Witness" do
        expect {
          post witnesses_url, params: { witness: invalid_attributes }
        }.to change(Witness, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post witnesses_url, params: { witness: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested witness" do
        witness = Witness.create! valid_attributes
        patch witness_url(witness), params: { witness: new_attributes }
        witness.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the witness" do
        witness = Witness.create! valid_attributes
        patch witness_url(witness), params: { witness: new_attributes }
        witness.reload
        expect(response).to redirect_to(witness_url(witness))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        witness = Witness.create! valid_attributes
        patch witness_url(witness), params: { witness: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested witness" do
      witness = Witness.create! valid_attributes
      expect {
        delete witness_url(witness)
      }.to change(Witness, :count).by(-1)
    end

    it "redirects to the witnesses list" do
      witness = Witness.create! valid_attributes
      delete witness_url(witness)
      expect(response).to redirect_to(witnesses_url)
    end
  end
end
