 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/workflowtemplates", type: :request do
  # Workflowtemplate. As you add validations to Workflowtemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Workflowtemplate.create! valid_attributes
      get workflowtemplates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      workflowtemplate = Workflowtemplate.create! valid_attributes
      get workflowtemplate_url(workflowtemplate)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_workflowtemplate_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      workflowtemplate = Workflowtemplate.create! valid_attributes
      get edit_workflowtemplate_url(workflowtemplate)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Workflowtemplate" do
        expect {
          post workflowtemplates_url, params: { workflowtemplate: valid_attributes }
        }.to change(Workflowtemplate, :count).by(1)
      end

      it "redirects to the created workflowtemplate" do
        post workflowtemplates_url, params: { workflowtemplate: valid_attributes }
        expect(response).to redirect_to(workflowtemplate_url(Workflowtemplate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Workflowtemplate" do
        expect {
          post workflowtemplates_url, params: { workflowtemplate: invalid_attributes }
        }.to change(Workflowtemplate, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post workflowtemplates_url, params: { workflowtemplate: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested workflowtemplate" do
        workflowtemplate = Workflowtemplate.create! valid_attributes
        patch workflowtemplate_url(workflowtemplate), params: { workflowtemplate: new_attributes }
        workflowtemplate.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the workflowtemplate" do
        workflowtemplate = Workflowtemplate.create! valid_attributes
        patch workflowtemplate_url(workflowtemplate), params: { workflowtemplate: new_attributes }
        workflowtemplate.reload
        expect(response).to redirect_to(workflowtemplate_url(workflowtemplate))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        workflowtemplate = Workflowtemplate.create! valid_attributes
        patch workflowtemplate_url(workflowtemplate), params: { workflowtemplate: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested workflowtemplate" do
      workflowtemplate = Workflowtemplate.create! valid_attributes
      expect {
        delete workflowtemplate_url(workflowtemplate)
      }.to change(Workflowtemplate, :count).by(-1)
    end

    it "redirects to the workflowtemplates list" do
      workflowtemplate = Workflowtemplate.create! valid_attributes
      delete workflowtemplate_url(workflowtemplate)
      expect(response).to redirect_to(workflowtemplates_url)
    end
  end
end
